CREATE TABLE "anticheat_definitions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "anticheat_definitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" varchar(32) NOT NULL,
	"key" varchar(32) NOT NULL,
	"parent_key" varchar(32) DEFAULT '' NOT NULL,
	"label" text NOT NULL,
	"description" text,
	"hint" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "anticheat_definitions_unique_entry" ON "anticheat_definitions" ("kind","key","parent_key");
--> statement-breakpoint
INSERT INTO "anticheat_definitions" ("kind","key","parent_key","label","description","hint") VALUES
('ruleType','0','','Event rate limit','Limits how many events of one type a player can fire per time window.',NULL),
('ruleType','1','','Movement speed limit','Limits how far a scene entity can move within a time window.',NULL),
('ruleField','0','0','Event type',NULL,'Which event is being limited'),
('ruleField','1','0','Max count',NULL,'Max events allowed per window'),
('ruleField','2','0','Window',NULL,'Time window in seconds'),
('ruleField','0','1','Max distance',NULL,'Max movement in px per window'),
('ruleField','1','1','Window',NULL,'Time window in seconds'),
('ruleField','2','1','Entity type',NULL,'0 = all types'),
('eventName','0','','Debug changed',NULL,NULL),
('eventName','1','','Server authenticated',NULL,NULL),
('eventName','2','','Server connected',NULL,NULL),
('eventName','3','','Server notification',NULL,NULL),
('eventName','4','','Server disconnected',NULL,NULL),
('eventName','5','','Match advertised',NULL,NULL),
('eventName','6','','Player connected',NULL,NULL),
('eventName','7','','Host disconnected',NULL,NULL),
('eventName','8','','Player disconnected',NULL,NULL),
('eventName','9','','Countdown',NULL,NULL),
('eventName','10','','Goal scored',NULL,NULL),
('eventName','11','','Game over',NULL,NULL),
('eventName','12','','Boost pad consumed',NULL,NULL),
('eventName','13','','Matchmaking started',NULL,NULL),
('eventName','14','','Online players',NULL,NULL),
('eventName','15','','Car demolished',NULL,NULL),
('eventName','16','','Return to main menu',NULL,NULL),
('eventName','17','','Snow weather',NULL,NULL),
('eventName','18','','Player banned',NULL,NULL),
('eventName','19','','User banned by server',NULL,NULL),
('eventName','20','','User kicked by server',NULL,NULL),
('entityName','0','','All types',NULL,NULL),
('entityName','1','','Local car',NULL,NULL),
('entityName','2','','Remote car',NULL,NULL),
('entityName','3','','NPC car',NULL,NULL),
('entityName','4','','Goal',NULL,NULL),
('entityName','5','','Goal explosion',NULL,NULL),
('entityName','6','','Car explosion',NULL,NULL),
('entityName','7','','Boost pad',NULL,NULL),
('entityName','10','','Scoreboard',NULL,NULL),
('entityName','11','','Alert',NULL,NULL),
('entityName','12','','Toast',NULL,NULL),
('entityName','13','','Help',NULL,NULL),
('entityName','14','','Match log',NULL,NULL),
('entityName','15','','Boost meter',NULL,NULL),
('entityName','20','','World background',NULL,NULL),
('valueType','0','','uint16',NULL,NULL),
('valueType','1','','float32',NULL,NULL)
ON CONFLICT ("kind","key","parent_key") DO NOTHING;
