export const ENV_GAME_URL = "GAME_URL";
export const ENV_JWT_SECRET = "JWT_SECRET";
export const ENV_CLOUDFLARE_CALLS_URL = "CLOUDFLARE_CALLS_URL";
export const ENV_CLOUDFLARE_CALLS_TOKEN = "CLOUDFLARE_CALLS_TOKEN";
export const ENV_DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN";
export const ENV_DISCORD_PUBLIC_KEY = "DISCORD_PUBLIC_KEY";
export const ENV_DISCORD_APPLICATION_ID = "DISCORD_APPLICATION_ID";
export const ENV_DISCORD_ALLOWED_ROLE_NAMES = "DISCORD_ALLOWED_ROLE_NAMES";

export const KV_GAMESERVER = "GAMESERVER_KV";
