/**
 * Augments the `Env` interfaces generated by `wrangler types` (both the global
 * `Env` and `Cloudflare.Env`, which is what `import { env } from
 * "cloudflare:workers"` returns) with the keys that only exist at runtime —
 * secrets set via `wrangler secret` and the local development `DATABASE_URL`.
 * They are optional here so the generated file stays authoritative for the
 * compile-time bindings.
 */
declare global {
  interface Env {
    DATABASE_URL?: string;
    JWT_SECRET?: string;
    CLOUDFLARE_CALLS_URL?: string;
    CLOUDFLARE_CALLS_TOKEN?: string;
    DISCORD_BOT_TOKEN?: string;
    DISCORD_PUBLIC_KEY?: string;
    DISCORD_APPLICATION_ID?: string;
    DISCORD_ALLOWED_ROLE_NAMES?: string;
    GAME_URL?: string;
  }

  namespace Cloudflare {
    interface Env {
      DATABASE_URL?: string;
      JWT_SECRET?: string;
      CLOUDFLARE_CALLS_URL?: string;
      CLOUDFLARE_CALLS_TOKEN?: string;
      DISCORD_BOT_TOKEN?: string;
      DISCORD_PUBLIC_KEY?: string;
      DISCORD_APPLICATION_ID?: string;
      DISCORD_ALLOWED_ROLE_NAMES?: string;
      GAME_URL?: string;
    }
  }
}

export {};