name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        description: Deployment target
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

permissions: {}

jobs:
  deploy-staging:
    if: >-
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'staging')
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      target: staging

  deploy-production:
    if: >-
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'production')
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      target: production
