name: Update database

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      checkout-ref:
        required: false
        type: string
        default: ""
      push-ref:
        required: false
        type: string
        default: ""
      concurrency-group:
        required: true
        type: string

concurrency:
  group: ${{ inputs.concurrency-group }}
  cancel-in-progress: true

jobs:
  update-database:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.checkout-ref }}
      - name: Set up Deno
        uses: denoland/setup-deno@v2
      - name: Generate schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: deno task generate
      - name: Push migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: deno task push
      - name: Commit schema changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "chore: update drizzle schema"
            git push ${{ inputs.push-ref }}
          fi
