name: Update Drizzle schema (Production)

on:
  push:
    branches:
      - main

concurrency:
  group: update-drizzle-production-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-drizzle:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Deno
        uses: denoland/setup-deno@v2
      - name: Generate schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: deno task generate
      - name: Push migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: deno task push
      - name: Commit schema changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "chore: update drizzle schema"
            git push
          fi
